


GET http://localhost:3000/flight HTTP/1.1

###

GET http://localhost:3000/flight/655c119f-f6b3-4bcd-b819-2d18aa64ead7 HTTP/1.1

###
POST http://localhost:3000/flight HTTP/1.1
Content-Type:  application/json

{
    "title": "flight to Canada",
    "price": "26000"
  
}


###


PUT http://localhost:3000/flight/655c119f-f6b3-4bcd-b819-2d18aa64ead7 HTTP/1.1
Content-Type:  application/json

{
    "title": "flight to Nigeria",
    "price": "26000"
}

###

DELETE  http://localhost:3000/flight/892180a3-60ee-45fa-a28d-9d770ca804fb HTTP/1.1
